:i
# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: trusty

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/sklearn
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
  include:
    # This environment tests that scikit-learn can be built against
    # versions of numpy, scipy with ATLAS that comes with Ubuntu Trusty 14.04
    - env: DISTRIB="ubuntu" PYTHON_VERSION="2.7" CYTHON_VERSION="0.23.4"
           COVERAGE=true
      addons:
        apt:
          packages:
            # these only required by the DISTRIB="ubuntu" builds:
            - python-scipy
            - libatlas3gf-base
            - libatlas-dev
    # This environment tests the oldest supported anaconda env
    - env: DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_MKL="false"
           NUMPY_VERSION="1.8.2" SCIPY_VERSION="0.13.3" CYTHON_VERSION="0.23.5"
           COVERAGE=true
    # This environment tests the newest supported Anaconda release (4.4.0)
    # It also runs tests requiring Pandas.
    - env: DISTRIB="conda" PYTHON_VERSION="3.6.1" INSTALL_MKL="true"
           NUMPY_VERSION="1.12.1" SCIPY_VERSION="0.19.0" PANDAS_VERSION="0.20.1"
           CYTHON_VERSION="0.25.2" COVERAGE=true
    # This environment use pytest to run the tests. It uses the newest
    # supported Anaconda release (4.4.0). It also runs tests requiring Pandas.
    - env: USE_PYTEST="true" DISTRIB="conda" PYTHON_VERSION="3.6.1"
           INSTALL_MKL="true" NUMPY_VERSION="1.12.1" SCIPY_VERSION="0.19.0"
           PANDAS_VERSION="0.20.1" CYTHON_VERSION="0.25.2"
    # flake8 linting on diff wrt common ancestor with upstream/master
    - env: RUN_FLAKE8="true" SKIP_TESTS="true"
           DISTRIB="conda" PYTHON_VERSION="3.5" INSTALL_MKL="true"
           NUMPY_VERSION="1.12.1" SCIPY_VERSION="0.19.0" CYTHON_VERSION="0.23.5"
           TEST_DOCSTRINGS="true"
    # This environment tests scikit-learn against numpy and scipy master
    # installed from their CI wheels in a virtualenv with the Python
    # interpreter provided by travis.
    -  python: 3.5
       env: DISTRIB="scipy-dev-wheels"
  allow_failures:
    # allow_failures seems to be keyed on the python version
    # We are using this to allow failures for DISTRIB=scipy-dev-wheels
    - python: 3.5

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
          global:
                     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
                     #    #   via the "travis encrypt" command using the project repo's public key
                     #       - secure: "Osigk3WSk8tNg4MzAzE/ce2howWpPYzhkxVL3+rKGEIXui2LZ1OYVeqeTSdr0oNStRCQ4DBcOXjyglNNk6hHRjZXLKEoISN5zxulOOO48ZysQtS3+lKX/yxGSYOeG3o3xdxWsgABNIzW9Ny3O4GOdPHyU3EvQ6yeXncQ+iLiu/08kGNQDUsF4tytZbQDWMyNElvx8pwIvnr10npTBKteJbfu27DpHJBsQ1G9nIw5kyD42NtCupULuLpE52/FgwMdn8FXP2SacH0FA7ctclRnEceJvbY0pJuWFjggi3t6dSvFcLNizLAZqUyWCotJXQGs2snXmeLgEII06V042IhBI9TWqSA+f+5LwmVPolx9Xm8osPL4M1XjKC92ACw7wzVV+K5xP9aq1TYqIB5Kmw3fFdTJxQSixoo3FGg1vOHoiMI0PrB34sBiYAXUvoz/dYWJTRxhqRmglmiFxXm6bexicHHZ5rBCkpn1G1kX/tLnQm4PZc25xEE8XyJ/lp2MRpByCEh92CgCKZZYAY7vELNfU5PP9/raOzjPsksWVqXZij0yPWP82kUw3oK7uDOgehrALDGPvcaAHt/PTAJU6Nuf6naJOxIoF95LYsCTiKaZkmhbn01GxKTb5CuQa238tZ1ZvKfJNCZkBjHTm/Z9kjOExcbWMJGXUQG5JeH+jvUqIuY="
                     #
                     #       before_install:
                     #             - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
                     #
                     #             addons:
                     #               coverity_scan:
                     #                   project:
                     #                         name: "chuacc22/scikit-learn"
                     #                               description: "Build submitted via Travis CI"
                     #                                   notification_email: clarence0622@gmail.com
                     #                                       build_command_prepend: "./configure; make clean"
                     #                                           build_command:   "make -j 4"
                     #                                               branch_pattern: coverity_scan:
